{{- if .Values.jellyseerr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "jellyseerr" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: {{ .Values.jellyseerr.image }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: PORT
              value: "5055"
          ports:
            - containerPort: 5055
              name: http
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
{{- end }}
