{{- if .Values.flaresolverr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "flaresolverr" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: {{ .Values.flaresolverr.image }}
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          ports:
            - containerPort: 8191
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: 8191
{{- end }}
