#!/usr/bin/env bash
set -e

echo "=== 1. Installing MicroK8s and Base Utilities ==="
sudo snap install microk8s --classic
sudo snap install helm --classic

# Add current user to microk8s group
sudo usermod -a -G microk8s $USER
mkdir -p ~/.kube
sudo chown -f -R $USER ~/.kube

# Set up alias for kubectl in .bashrc if not present
if ! grep -q "alias kubectl='microk8s kubectl'" ~/.bashrc; then
  echo "alias kubectl='microk8s kubectl'" >> ~/.bashrc
fi

echo "=== 2. Enabling MicroK8s Addons ==="
# Wait for MicroK8s core to be ready before enabling addons
sudo microk8s status --wait-ready
sudo microk8s enable dns
sudo microk8s enable hostpath-storage
sudo microk8s enable metrics-server

echo "=== 3. Configuring Host Systems and Directories ==="
# Disable systemd-resolved DNSStubListener to free port 53 for Pi-hole
sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
sudo systemctl restart systemd-resolved || true

# Shared Media Directories
sudo mkdir -p /srv/media/tv /srv/media/downloads /srv/media/movies
sudo chmod -R 777 /srv/media

# Service Storage Directories
sudo mkdir -p /srv/jellyfin/config /srv/jellyfin/tvshows /srv/jellyfin/movies
sudo chmod -R 777 /srv/jellyfin

sudo mkdir -p /srv/pihole/config
sudo chmod -R 777 /srv/pihole

sudo mkdir -p /srv/immich/upload /srv/immich/postgres
sudo chmod -R 777 /srv/immich

echo "=== 4. Applying Cluster Services ==="

# Homepage (folder manifests)
if [ -d "./homepage" ]; then
  echo "Applying Homepage..."
  sudo microk8s kubectl apply -f ./homepage/
fi

# Core workloads
[ -f "pihole.yaml" ] && echo "Applying Pi-hole..." && sudo microk8s kubectl apply -f pihole.yaml
[ -f "immich.yaml" ] && echo "Applying Immich..." && sudo microk8s kubectl apply -f immich.yaml
[ -f "jellyfin.yaml" ] && echo "Applying Jellyfin..." && sudo microk8s kubectl apply -f jellyfin.yaml
[ -f "sonarr.yaml" ] && echo "Applying Sonarr..." && sudo microk8s kubectl apply -f sonarr.yaml
[ -f "qbittorrent.yaml" ] && echo "Applying qBittorrent..." && sudo microk8s kubectl apply -f qbittorrent.yaml

echo "=== 5. Applying qBittorrent Web UI Fix ==="
if [ -f "qbittorrent.yaml" ]; then
  echo "Waiting for qBittorrent config file to be generated on hostpath..."
  
  # Loop until the config file is generated by the pod startup
  STORAGE_BASE="/var/snap/microk8s/common/default-storage"
  CONF_FILE=""
  for i in {1..30}; do
    CONF_FILE=$(sudo find "$STORAGE_BASE" -name "qBittorrent.conf" 2>/dev/null | head -n 1)
    if [ -n "$CONF_FILE" ]; then
      break
    fi
    sleep 2
  done

  if [ -n "$CONF_FILE" ]; then
    echo "Found $CONF_FILE. Disabling WebUI Host Header Validation..."
    # Temporarily stop pod so qBittorrent doesn't overwrite file on exit
    sudo microk8s kubectl scale deployment qbittorrent --replicas=0
    sudo sed -i '/\[Preferences\]/a WebUI\\HostHeaderValidation=false\nWebUI\\CSRFProtection=false' "$CONF_FILE"
    sudo microk8s kubectl scale deployment qbittorrent --replicas=1
    echo "qBittorrent Web UI bypass successfully applied!"
  else
    echo "Warning: Could not locate qBittorrent.conf within time limit. Apply bypass manually if needed."
  fi
fi

echo "=== Setup Complete ==="
echo "All manifests applied successfully!"