apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: default
  labels:
    app.kubernetes.io/name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          env:
            - name: TZ
              value: "America/Bogota"
            - name: PORT
              value: "5055"
          ports:
            - containerPort: 5055
              name: http
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      nodePort: 30055
