{{- if and (not .Values.infisical.existingCredentialsSecret) (not .Values.infisicalServer.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab.infisicalSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "infisical" "Release" .Release) | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.infisical.clientId | quote }}
  clientSecret: {{ .Values.infisical.clientSecret | quote }}
  projectId: {{ .Values.infisical.projectId | quote }}
{{- end }}
