{{- if .Values.homepage.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: homepage-infisical-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "homepage" "Release" .Release) | nindent 4 }}
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsRef:
        secretName: {{ include "homelab.infisicalSecretName" . }}
        secretNamespace: {{ .Release.Namespace }}
  managedSecretRef:
    secretName: homepage-api-keys
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
{{- end }}
