{{- if .Values.bazarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "bazarr" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: {{ .Values.bazarr.image }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          ports:
            - containerPort: 6767
              name: http
          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: /srv/media/tv
              name: media-tvshows
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: media-tvshows
          hostPath:
            path: {{ .Values.bazarr.storage.tvPath }}
            type: Directory
{{- end }}
