{{- if and .Values.homepage.enabled .Values.homepage.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "homepage" "Release" .Release) | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
{{- end }}
