{{- if .Values.pihole.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "pihole" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: {{ .Values.pihole.image }}
          securityContext:
            runAsUser: 0
          env:
            - name: TZ
              value: {{ .Values.pihole.timezone | quote }}
            - name: FTLCONF_webserver_active
              value: "true"
            - name: FTLCONF_webserver_port
              value: {{ printf "%v,%vs" .Values.pihole.webPort "8443" | quote }}
            - name: FTLCONF_webserver_api_password
              value: {{ .Values.pihole.webPassword | quote }}
            - name: FTLCONF_webserver_domain
              value: ""
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
      volumes:
        - name: pihole-config
          hostPath:
            path: {{ .Values.pihole.storage.configPath }}
            type: DirectoryOrCreate
{{- end }}
