{{- if .Values.jellyfin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "jellyfin" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: {{ .Values.jellyfin.image }}
          ports:
            - containerPort: 8096
              name: http
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /data/tvshows
              name: media-tvshows
            - mountPath: /data/movies
              name: media-movies
      volumes:
        - name: jellyfin-config
          hostPath:
            path: {{ .Values.jellyfin.storage.configPath }}
            type: Directory
        - name: media-tvshows
          hostPath:
            path: {{ .Values.jellyfin.storage.tvPath }}
            type: Directory
        - name: media-movies
          hostPath:
            path: {{ .Values.jellyfin.storage.moviesPath }}
            type: Directory
{{- end }}
