{{- if .Values.prowlarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "prowlarr" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: {{ .Values.prowlarr.image }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          ports:
            - containerPort: 9696
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
{{- end }}
