{{- if .Values.qbittorrent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" (dict "name" "qbittorrent" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: {{ .Values.qbittorrent.image }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: WEBUI_PORT
              value: {{ .Values.qbittorrent.service.webuiNodePort | quote }}
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - containerPort: {{ .Values.qbittorrent.service.webuiNodePort }}
              name: webui
            - containerPort: 6881
              name: torrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: media-downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: media-downloads
          hostPath:
            path: {{ .Values.qbittorrent.storage.downloadsPath }}
            type: DirectoryOrCreate
{{- end }}
